---
- name: install default-jdk git maven
  hosts: buildapp
  become: yes
  tasks: 
    - name: Update repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install default-jdk git maven
      apt:
        pkg: 
          - default-jdk
          - git
          - maven


- name: Build application
  hosts: buildapp
  tasks:
    - name: Create app
      git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git 
       dest: /tmp/boxfuse-sample-java-war-hello/
    - name: build app maven
      command: mvn package
      args:
       chdir: /tmp/boxfuse-sample-java-war-hello/